module.exports = {
  caseType:'permissioned_memory_corpus_delivery', initialState:'source_registered',
  states:['source_registered','ingestion_queued','parsed','deduplicated','indexed','retrieval_evaluated','human_review','publish_approved','print_package_review','print_job_queued','delivered','deletion_pending','deleted'],
  createRoles:['book_owner','archivist'],
  assessmentRoles:['archivist','editor','book_owner','privacy_reviewer'],
  auditRoles:['book_owner','privacy_reviewer'],
  connectorRoles:['book_owner','integration_operator'],
  evidenceKinds:['source_manifest','ingestion_checkpoint','object_digest','parser_manifest','chunk_manifest','deduplication_report','permission_snapshot','index_manifest','retrieval_evaluation','citation_resolution','injection_scan','human_disposition','print_package_manifest','print_job_receipt','deletion_receipt'],
  requiredSignals:['sourceVersion','indexVersion','permissionVersion','datasetVersion','retrievalRecall','faithfulness','citationResolution','freshnessStatus','injectionScanStatus','policyVersion'],
  professionalBoundary:'Generated narratives and answers must cite authorized sources and abstain when evidence is weak; families/editors approve publication and rights.',
  connectors:[
    {name:'repository_api',purpose:'resumable source and deletion receipts'},
    {name:'object_storage',purpose:'encrypted immutable source pointers'},
    {name:'parser_queue',purpose:'versioned parse/chunk jobs'},
    {name:'search_index',purpose:'permission-filtered index manifests'},
    {name:'print_vendor',purpose:'approved print job receipts'},
    {name:'notification',purpose:'collaborator and delivery receipts'},
  ],
  transitions:[
    {from:'source_registered',action:'queue_ingestion',to:'ingestion_queued',roles:['archivist'],requiresEvidence:true},
    {from:'ingestion_queued',action:'record_parse',to:'parsed',roles:['archivist'],requiresEvidence:true},
    {from:'parsed',action:'record_deduplication',to:'deduplicated',roles:['archivist'],requiresEvidence:true},
    {from:'deduplicated',action:'record_index',to:'indexed',roles:['archivist'],requiresEvidence:true},
    {from:'indexed',action:'record_evaluation',to:'retrieval_evaluated',roles:['editor','archivist'],requiresEvidence:true},
    {from:'retrieval_evaluated',action:'submit_human_review',to:'human_review',roles:['editor'],requiresEvidence:true},
    {from:'human_review',action:'approve_publish',to:'publish_approved',roles:['book_owner','privacy_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'publish_approved',action:'review_print_package',to:'print_package_review',roles:['editor'],requiresEvidence:true},
    {from:'print_package_review',action:'queue_print',to:'print_job_queued',roles:['book_owner'],requiresEvidence:true,dualControl:true},
    {from:'print_job_queued',action:'record_delivery',to:'delivered',roles:['book_owner'],requiresEvidence:true},
    {from:'source_registered',action:'request_deletion',to:'deletion_pending',roles:['book_owner','privacy_reviewer'],requiresEvidence:true},
    {from:'delivered',action:'request_deletion',to:'deletion_pending',roles:['book_owner','privacy_reviewer'],requiresEvidence:true},
    {from:'deletion_pending',action:'confirm_deletion',to:'deleted',roles:['privacy_reviewer'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const recall=Number(x.retrievalRecall);const faith=Number(x.faithfulness);const valid=[recall,faith].every(v=>Number.isFinite(v)&&v>=0&&v<=1);const accepted=valid&&recall>=0.8&&faith>=0.9&&x.citationResolution==='resolved'&&x.freshnessStatus==='current'&&x.injectionScanStatus==='passed';return{disposition:accepted?'human_publication_review_required':'abstain_and_reindex_or_review',answer:null,abstain:!accepted,versions:{source:x.sourceVersion,index:x.indexVersion,permissions:x.permissionVersion,dataset:x.datasetVersion}};},
};
