const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {createWorkflow}=require('./workflowCore');const {validateRuntime}=require('./runtime');const config=require('./config');const workflow=createWorkflow(config);const headers={'x-tenant-id':'family-a','idempotency-key':'request-a'};
const accepted={sourceVersion:'source-v3',indexVersion:'index-v4',permissionVersion:'acl-v2',datasetVersion:'eval-v5',retrievalRecall:0.9,faithfulness:0.95,citationResolution:'resolved',freshnessStatus:'current',injectionScanStatus:'passed',policyVersion:'policy-v1'};
test('permissioned corpus topology and connectors are declared',()=>{assert.ok(config.states.includes(config.initialState));assert.ok(config.transitions.length>2);assert.ok(config.connectors.length>2);for(const r of config.transitions){assert.ok(config.states.includes(r.from));assert.ok(config.states.includes(r.to));assert.ok(r.roles.length);}});
test('tenant, idempotency, actor and document owner roles fail closed',()=>{assert.throws(()=>workflow.context({}, {id:'a',role:'archivist'}),/X-Tenant-Id/);const c=workflow.context(headers,{id:'archivist-a',role:'archivist'});assert.equal(workflow.createCase({subjectRef:'book-17',policyVersion:'p-v1',effectiveAt:'2026-07-18T00:00:00Z',retentionUntil:'2027-07-18T00:00:00Z'},c).state,config.initialState);assert.throws(()=>workflow.createCase({subjectRef:'book-17',policyVersion:'p-v1',effectiveAt:'2026-07-18T00:00:00Z'},{...c,role:'visitor'}),/Role cannot create/);});
test('source evidence is opaque and digest verified',()=>{assert.equal(workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'vault:memory-17',sourceVersion:'v1',sha256:'a'.repeat(64),capturedAt:'2026-07-18T10:00:00Z'}).sha256,'a'.repeat(64));assert.throws(()=>workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'vault:x',sourceVersion:'v1',sha256:'bad',capturedAt:'2026-07-18T10:00:00Z'}),/sha256/);});
test('grounded current retrieval requires human publication review and otherwise abstains',()=>{const c=workflow.context(headers,{id:'archivist-a',role:'archivist'});assert.equal(workflow.deterministicAssessment({},c).disposition,'insufficient_evidence');const good=workflow.deterministicAssessment(accepted,c);assert.equal(good.disposition,'human_publication_review_required');assert.equal(good.answer,null);assert.equal(good.abstain,false);assert.equal(good.automatedDecision,false);const held=workflow.deterministicAssessment({...accepted,injectionScanStatus:'failed'},c);assert.equal(held.disposition,'abstain_and_reindex_or_review');assert.equal(held.abstain,true);});
test('transitions require evidence, versions and privacy dual control',()=>{const r=config.transitions[0];const c=workflow.context(headers,{id:'actor-b',role:r.roles[0]});const rec={state:r.from,version:1,evidenceCount:0,createdBy:'actor-a',lastActorId:null};assert.throws(()=>workflow.transition(rec,{action:r.action,expectedVersion:1,reason:'queued resumable ingestion'},c),/evidence/);assert.throws(()=>workflow.transition({...rec,evidenceCount:1},{action:r.action,expectedVersion:2,reason:'queued resumable ingestion'},c),/changed/);assert.equal(workflow.transition({...rec,evidenceCount:1},{action:r.action,expectedVersion:1,reason:'queued resumable ingestion'},c).to,r.to);const d=config.transitions.find(x=>x.dualControl);const dc=workflow.context(headers,{id:'actor-b',role:d.roles[0]});assert.throws(()=>workflow.transition({state:d.from,version:2,evidenceCount:1,createdBy:'actor-a',lastActorId:'actor-b'},{action:d.action,expectedVersion:2,reason:'independent privacy approval'},dc),/second person/);});
test('runtime safety rejects weak or demo production config',()=>{assert.throws(()=>validateRuntime({NODE_ENV:'test',JWT_SECRET:'short'}),/JWT_SECRET/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'*'}),/allowlist/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'https://client.example',ALLOW_DEMO_SEED:'true'}),/prohibited/);assert.equal(validateRuntime({NODE_ENV:'test',JWT_SECRET:'x'.repeat(40)}),true);});
test('migration and launcher are append-only and nondestructive',()=>{const root=path.resolve(__dirname,'..','..');const m=fs.readFileSync(path.join(root,'backend/migrations/001_governed_ingestion.sql'),'utf8');const s=fs.readFileSync(path.join(root,'start.sh'),'utf8');assert.match(m,/governed_tenant_memberships/);assert.match(m,/governed_connector_failures/);assert.match(m,/append-only/);assert.doesNotMatch(s,/kill\s+-9|pkill|dropdb|createdb|npm\s+install|seed\.js|psql\s+.*-f/);});
